### ISSUE TITLE
RMC controllers 

### ISSUE THREAD

**Issue by m-nieto** [numat/watlow#11]
Would this Python code work with the EZ-ZONE controllers for rail mount, with no display or buttons? This would be the RMC series of the EZ-ZONE family of controllers. I have one of those with 4 zones and would like to write Python code to communicate with it via MODBUS RTU.

**Comment by JamesJeffryes** [comment]
There are two controllers in this driver. The first (TemperatureController) was reverse-engineered to control a Watlow PM over the inter-module bus. There's a chance this would work for you IF your RMC is in zone 1 AND you correctly wire the between the RMC and the python device but I don't recommend it.

Eventually, we needed to control several of these devices so we invested in the Watlow Gateway (~$350 at the time) and wrote the Gateway controller that sets the gateway over Modbus and propagates the commands to the controllers over the inter-module bus. If that is a reasonable approach, all you will have to do is configure the gateway to match the expected modbus offsets.

On the other hand, It looks like the RMCs support Modbus directly (unlike the PMs this was written for) so you may be able to bypass the need for a gateway entirely. You will have to extend the driver with a new controller to handle the new Modbus addresses which are on pg 316 of the RMC manual. I recommend using the [Gateway implementation](https://github.com/numat/watlow/blob/master/watlow/driver.py#L151) as a starting point. If you do build this out, please open a PR here so others can benefit.

Finally, if you just need logging, buying [dedicated software](https://www.watlow.com/products/controllers/software) could make the most sense.

**Comment by m-nieto** [comment]
Thanks for your answer, James. Indeed, after some experimentation it turns out that these series have native MODBUS support. So the gateway was not required

**Comment by JamesJeffryes** [comment]
Wonderful! I'm going to close this issue but do feel free to submit a PR if you implement a driver for RMC controllers and want to contribute it upstream
