### ISSUE TITLE
Would any RS485 to USB converter work to interface?

### ISSUE THREAD

**Issue by igniscyan** [numat/watlow#4]
Sorry for posting an issue on this, but I'm wanting to get something setup at my workplace with this. I have a model PM6C1FJ-AAAAAAA EZ-Zone. The model guide is a little confusing; am I to understand I don't have the additional module, but can still connect and use this library as long as I have a RS485 to USB converter? Will any of these converters work? 

Thanks!

**Comment by patrickfuller** [comment]
That's (probably) right! We've used this with an adapter and Raspberry Pi to make it remotely controllable + loggable.

We have since bought their Modbus gateways as we have many Watlows running now, but the cable/Pi solution worked well for us for a couple of years.

Hope this helps!

**Comment by igniscyan** [comment]
Thanks so much for the reply! 

Awesome, I guess the last question I have is if you have an adapter you recommend. In the ancient "thats EZ!" tutorial they show an adapter that has extremely odd polarity markings, with two A- and two B+. I can't find anything on Amazon that remotely matches that. Is that adapter proprietary? Any insight on this would be appreciated :).

**Comment by patrickfuller** [comment]
We used [these](https://www.amazon.com/Gearmo-Pro-RS485-RS422-FTDI-Chip/dp/B005CPLOVW/ref=sr_1_3?dchild=1&keywords=rs-485+to+usb&qid=1623442901&sr=8-3). We were using Watlows within bigger pieces of equipment. Some worked as is and some required changing the pinout. We use [these screw terminal DB9s](https://www.amazon.com/Breakout-Connector-BIFALE-Solderless-Adapters/dp/B08P77JSYF/ref=sr_1_3?dchild=1&keywords=db9+screw+terminal&qid=1623442953&sr=8-3) for quick pinout changes before soldering one.

Good luck!

**Comment by igniscyan** [comment]
Awesome, ordered both. Do you have a reference for how this converter is supposed to be wired to the watlow? My watlow has the CF, CD, and CE communication output. Information on this is a little scarce, sorry for all the questions.

**Comment by igniscyan** [comment]
Ended up finding an old pinout guide on some random forum! Thank you so much for the help/nudge in the right direction :)
