### ISSUE TITLE
Set temperature beyond 200C

### ISSUE THREAD

**Issue by igniscyan** [numat/watlow#5]
Hi there!

Sorry for the second issue, trying to get this implemented and just noticed there is a hard limit on the range the temperature can be set. I was wondering if this was something that could be circumvented as our Watlow is usually set to as much as 2275 degrees (Fahrenheit). 

Any info on this would be greatly appreciated! 

Edit: Would also like to ask, will there be issues if our device is configured to work in Fahrenheit rather than Celsius?

**Comment by patrickfuller** [comment]
@igniscyan short term, it should be as easy as deleting [these lines](https://github.com/numat/watlow/blob/master/watlow/driver.py#L106-L107).

@JamesJeffryes what do you think about removing this check from the driver layer? It seems better suited for a subclass/interface, right?

**Comment by igniscyan** [comment]
I am noticing that in commit f29ca110bb0ca92024f882d4b120d1cc8992f20a this range was modified. Looking at function, it appears as though the temperatures are converted to Fahrenheit when being packed for the Watlow, correct? Would getting this function to work as Fahrenheit be as simple as directly passing the value in F to the packing method, getting rid of the C_to_F method?

```python
 body = self.commands['set']['body'] + struct.pack('&gt;f', c_to_f(setpoint))
```

**Comment by igniscyan** [comment]
> @igniscyan short term, it should be as easy as deleting [these lines](https://github.com/numat/watlow/blob/master/watlow/driver.py#L106-L107).
> 
> @JamesJeffryes what do you think about removing this check from the driver layer? It seems better suited for a subclass/interface, right?

You beat me to it :)

**Comment by igniscyan** [comment]
Don't want to open a new issue, but I'm being greeted with port not open on /dev/ttyusb0 now even though it has been set to open in Raspi config. I know this is the exact use case you had so I thought I'd ask, any idea if I'm missing something? Wired to watlow as specified in the  pinout for my model.

**Comment by igniscyan** [comment]
@JamesJeffryes 

Hey there! Sorry for the lapse in getting stuff submitted for this, work has been a little crazy.


I will have some free time this weekend, but just wanted to point out there is still 1 temperature check that was causing issues for me until I modified it: 
`        temperature = f_to_c(struct.unpack('>f', unhexlify(value))[0])
        if temperature < 0 or temperature > 250:
            return self._write_and_read(request, length, check, retries-1)
        return temperature`

This will cause the program to error out if you use anything out of range. 


I can make a PR this weekend with a wiki including a lot of the writeup @patrickfuller sent me and throw this change in there as well. 

Best,

Brandon
