### ISSUE TITLE
Controlling more than set point

### ISSUE THREAD

**Issue by Fluff44** [numat/watlow#9]
Hi,

I am making my own controller that controls a Watlow and some other equipment together and I need the serial registeries for the ramp rate and the control loop on/off. This is the closest I have seen to them being reported somewhere.

I managered to work back from the documented parameter IDs and instances and got the ramp rate. It is:
0104 0711 0108 + value , very similar to the way you change the set point: 0104 0701 0108 + value. However, I have been unable to get the control loop on/off value (80001 in the documentation).

I also would like some more information to how you got this format for the serial driver:

    Preamble Req/Res Zone ???         Check ???        Register Instance Value       Check
    55ff          05          10      000006 e8        010301 0401      01         00000000 e399

This is only my second serial project and I am not formally trained in any programming language, so it might be something pretty simple.

Thanks,

Resolved, the on/off commands have different ??? sections: Here is my guess for how to adjust them.

Preamble Req/Res Zone ???      Check  ???        Register Instance Value       Check
55ff          05         10       0300  0946     0114     0801      01          0f01000a  4027
55ff          05         10       0300  0946     0114     0801      01          0f01003e  e750

Hopefully this helps someone else!

**Comment by alexrudd2** [comment]
@Fluff44 I didn't do the original code, but try reading [this StackOverflow post](https://reverseengineering.stackexchange.com/questions/8303/rs-485-checksum-reverse-engineering-watlow-ez-zone-pm).

**Comment by Fluff44** [comment]
@alexrudd2 I already solved the issue and posted how I did it (see the edit at the bottom). I actually used the method you linked to.

Thanks!
